# Generated by Django 5.0.1 on 2024-03-22 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 3, 23)),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 22)),
        ),
    ]
