# Generated by Django 5.0.1 on 2024-03-24 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='status_color',
            field=models.TextField(default='red accent-3', max_length=40),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 3, 25), verbose_name='checkpoint end date'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 3, 25)),
        ),
    ]
