# Generated by Django 5.0.1 on 2024-03-26 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_checkpoint_status_color_alter_checkpoint_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 3, 27), verbose_name='checkpoint end date'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 3, 27)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
