# Generated by Django 5.0.1 on 2024-03-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_status_checkpoint_is_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='status_color',
        ),
    ]
